### ISSUE TITLE
Generated pngs don't include all the data

### ISSUE THREAD

**Issue by axilleas** [joergsteinkamp/visualize-ssh-failed-logins#2]
Could it be the version of R? I'm on `3.1.3`.

As you can see from the output:

```
> ### get the data from the database
> query   <- dbSendQuery(dbcon, "SELECT * FROM event")
> events  <- dbFetch(query)
> dummy   <- dbClearResult(query)
> message(nrow(events))
500
> 
> query   <- dbSendQuery(dbcon, "SELECT * FROM ip")
> ips     <- dbFetch(query)
> dummy   <- dbClearResult(query)
> message(nrow(ips))
272
> 
> query   <- dbSendQuery(dbcon, "SELECT * FROM user")
> users   <- dbFetch(query)
> dummy   <- dbClearResult(query)
> message(nrow(users))
500
> 
> query   <- dbSendQuery(dbcon, "SELECT * FROM subnet")
> subnets <- dbFetch(query)
> dummy   <- dbClearResult(query)
> message(nrow(subnets))
81
```

there are recorded 

| number | table |
| --- | --- |
| 500 | events |
| 500 | users |
| 81 | subnets |
| 272 | IPs. |

If I manually search the db, I get the following entries

| number | table |
| --- | --- |
| 140.670 | events |
| 980 | users |
| 81 | subnets |
| 272 | IPs |

And in the end, I end up with the following images.

![map](https://cloud.githubusercontent.com/assets/340023/6988013/d1d7d704-da55-11e4-9780-aea87f44b780.png)
![country](https://cloud.githubusercontent.com/assets/340023/6988011/d1d59c6e-da55-11e4-8055-5c41d5fd5333.png)
![subnet](https://cloud.githubusercontent.com/assets/340023/6988012/d1d7d1fa-da55-11e4-9a5d-954e792b4b11.png)
![user](https://cloud.githubusercontent.com/assets/340023/6988009/d1d20a40-da55-11e4-832c-4ad81321fd63.png)
![ts](https://cloud.githubusercontent.com/assets/340023/6988010/d1d3d104-da55-11e4-814b-02806344437f.png)

**Comment by joergsteinkamp** [comment]
Within each "p <- ggplot([...])" command is a "subset" command, which filters the input. You can remove it to use the full database, e.g. line 122
p <- ggplot(subset(users, name!="" & N>1), aes(x=name, y=N, fill=name))
will become
p <- ggplot(users, aes(x=name, y=N, fill=name))
and so on. However, I don't understand what's wrong with your map, since there is no subset included. Can you mail me your database?

**Comment by axilleas** [comment]
Thanks for your time looking into this :)

So, I used your instructions and managed to get more info out of the graphs, although a lot cluttered since the data are too much :p 

Anyway, here's a link to my db for you to investigate 

```
https://files.espiv.net/bulgbvqtdgmz3pdz2y4k-pkvysrakivmwo7bo
```

Again, thanks a lot for your time.

**Comment by joergsteinkamp** [comment]
I added a comment to the visualization section in the R script, that the subset and/or graphic size has to be adjusted. Were you able to get a colored map?
