### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, "N", value = NA) in visualize.R

### ISSUE THREAD

**Issue by harmverbeek** [joergsteinkamp/visualize-ssh-failed-logins#3]
I get the following error in visualize.R:

Error in `$<-.data.frame`(`*tmp*`, "N", value = NA) : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted

It is cause by this part of the code:

subnets$N <- NA
for (i in 1:nrow(subnets)) {
  subnets$N[i] = nrow(subset(events, subnetid==subnets$id[i]))
}

Unfortunately I don't know R very well.
I was hoping this code would run out-of-the box.

**Comment by joergsteinkamp** [comment]
Hi,

It means your data.frame contains no data. Put the following statement before the for-loop to check:
print(str(subnets))
it gives you information about the structure of the data. If you don't understand it, reply again including the output from the above statement, as well as "print(str(events))". Then I can try to help again.

Jörg

---

This email was written and sent on the road
